/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import javax.swing.JOptionPane;

/**
 *
 * @author Karl
 */
public class Contacts extends javax.swing.JFrame {
   
    
    String name, question;
    int studentNum;
    
    //declare array of objects
     ArrayQuestion[] arr;
     
     //declare counter
     int count;
    
    /**
     * Creates new form Contacts
     */
    public Contacts() {
        initComponents();
       
        //create array
        arr = new ArrayQuestion[4];
        //initialize count
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        backBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        studentNumLbl = new javax.swing.JLabel();
        questionLbl = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        studentNumTextField = new javax.swing.JTextField();
        questionTextField = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        computingSupportTutorLbl = new javax.swing.JLabel();
        francisSheridan = new javax.swing.JLabel();
        francisImg = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/BackArrow.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        backBtn.setBounds(40, 450, 100, 40);
        jLayeredPane1.add(backBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nameLbl.setText("Name:");
        nameLbl.setBounds(90, 350, 53, 20);
        jLayeredPane1.add(nameLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        studentNumLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        studentNumLbl.setText("Student Number:");
        studentNumLbl.setBounds(10, 380, 140, 20);
        jLayeredPane1.add(studentNumLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        questionLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        questionLbl.setText("Question:");
        questionLbl.setBounds(70, 410, 80, 20);
        jLayeredPane1.add(questionLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        addBtn.setText("Add Question");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        addBtn.setBounds(170, 440, 110, 23);
        jLayeredPane1.add(addBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });
        displayBtn.setBounds(300, 440, 110, 23);
        jLayeredPane1.add(displayBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Do you have a question for Francis? ");
        jLabel8.setBounds(90, 320, 300, 20);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        nameTextField.setBounds(170, 350, 240, 20);
        jLayeredPane1.add(nameTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        studentNumTextField.setBounds(170, 380, 240, 20);
        jLayeredPane1.add(studentNumTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        questionTextField.setBounds(170, 410, 240, 20);
        jLayeredPane1.add(questionTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        emailLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        emailLbl.setText("Email: computingsupport@ncirl.ie");
        emailLbl.setBounds(180, 240, 310, 40);
        jLayeredPane1.add(emailLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        phoneLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        phoneLbl.setText("Phone: (01) 6599260 ");
        phoneLbl.setBounds(220, 210, 180, 20);
        jLayeredPane1.add(phoneLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        computingSupportTutorLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        computingSupportTutorLbl.setText("Computing Support Tutor");
        computingSupportTutorLbl.setBounds(210, 170, 210, 30);
        jLayeredPane1.add(computingSupportTutorLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        francisSheridan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        francisSheridan.setForeground(new java.awt.Color(255, 255, 255));
        francisSheridan.setText("Francis Sheridan");
        francisSheridan.setBounds(210, 120, 200, 40);
        jLayeredPane1.add(francisSheridan, javax.swing.JLayeredPane.DEFAULT_LAYER);

        francisImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/FrancisPNG.png"))); // NOI18N
        francisImg.setBounds(20, 110, 160, 206);
        jLayeredPane1.add(francisImg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Computing Contact text.png"))); // NOI18N
        title.setBounds(70, -10, 320, 110);
        jLayeredPane1.add(title, javax.swing.JLayeredPane.DEFAULT_LAYER);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/886292_10200232032457361_1800231072_o.jpg"))); // NOI18N
        background.setBounds(0, 0, 460, 510);
        jLayeredPane1.add(background, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        dispose();
ComputingMain myComputingMain = new ComputingMain ();
myComputingMain.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
         //declare object
         ArrayQuestion a;
          //create object
        a = new ArrayQuestion();
        //get text from textfields
        name = nameTextField.getText();
        question = questionTextField.getText();
        studentNum = Integer.parseInt(studentNumTextField.getText());
        
        a.setName(name);
        a.setQuestion(question);
        a.setStudentNum(studentNum);
        
        arr[count] = a;
        count++;
        
        
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        //loop through
        for(int i = 0; i < arr.length; i = i +1){
        JOptionPane.showMessageDialog(null, "Name: "+arr[i].getName()+"\n Student Number: "+arr[i].getStudentNum()+"\n Question: "+arr[i].getQuestion());
    }
    }//GEN-LAST:event_displayBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contacts().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel background;
    private javax.swing.JLabel computingSupportTutorLbl;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel francisImg;
    private javax.swing.JLabel francisSheridan;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JTextField questionTextField;
    private javax.swing.JLabel studentNumLbl;
    private javax.swing.JTextField studentNumTextField;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
